Description: >
    Carlos Rivas / Udacity 2019

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

  AMItoUse:
    Description: AMI to use for our base image
    Type: String
    Default: ami-0c4f7023847b90238

Resources:
  RoleForSSMAccess:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
         - Effect: Allow
           Action:
             - 'sts:AssumeRole'
           Principal:
            Service:
              - ec2.amazonaws.com
            
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
# Instance Profile
  ServerInstanceProfile: 
    Type: "AWS::IAM::InstanceProfile"
    Properties: 
      Roles: 
        - !Ref RoleForSSMAccess

  WebServerSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow inbound access on port 80 and ssh. From specific IP.
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 160.119.127.165/32
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 160.119.127.165/32
      SecurityGroupEgress:
      - IpProtocol: All
        FromPort: 0
        ToPort: 65535
        CidrIp: 0.0.0.0/0

  myWebServerInstance: 
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: 
        Ref: AMItoUse
      KeyName: "thirdKeyPair"
      IamInstanceProfile: !Ref ServerInstanceProfile
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "True"
          DeviceIndex: "0"
          GroupSet: 
            - Ref: "WebServerSecGroup"
          SubnetId: 
            Fn::ImportValue:
              !Sub "${EnvironmentName}-PUB-NET"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt-get update -y
          sudo apt-get install apache2 -y
          sudo systemctl start apache2.service
          echo "Gerald Demo web server for Project 2 up and Running!!" > /var/www/html/index.html 
          sudo apt-get install awscli -y
          aws s3 cp s3://udagram241921546343/Sample.html index.html